// Auto-generated by scripts/build-gallery.js — do not edit by hand.
// Re-run "node scripts/build-gallery.js" after adding/removing photos in /gallery.
window.GALLERY_PHOTOS = [
  {
    "id": "IMG_3552",
    "thumb": "gallery-optimized/thumb/IMG_3552.webp",
    "large": "gallery-optimized/large/IMG_3552.webp"
  },
  {
    "id": "IMG_3558",
    "thumb": "gallery-optimized/thumb/IMG_3558.webp",
    "large": "gallery-optimized/large/IMG_3558.webp"
  },
  {
    "id": "IMG_3561",
    "thumb": "gallery-optimized/thumb/IMG_3561.webp",
    "large": "gallery-optimized/large/IMG_3561.webp"
  },
  {
    "id": "IMG_3567",
    "thumb": "gallery-optimized/thumb/IMG_3567.webp",
    "large": "gallery-optimized/large/IMG_3567.webp"
  },
  {
    "id": "IMG_3569",
    "thumb": "gallery-optimized/thumb/IMG_3569.webp",
    "large": "gallery-optimized/large/IMG_3569.webp"
  },
  {
    "id": "IMG_3571",
    "thumb": "gallery-optimized/thumb/IMG_3571.webp",
    "large": "gallery-optimized/large/IMG_3571.webp"
  },
  {
    "id": "IMG_3572",
    "thumb": "gallery-optimized/thumb/IMG_3572.webp",
    "large": "gallery-optimized/large/IMG_3572.webp"
  },
  {
    "id": "IMG_3575",
    "thumb": "gallery-optimized/thumb/IMG_3575.webp",
    "large": "gallery-optimized/large/IMG_3575.webp"
  },
  {
    "id": "IMG_3576",
    "thumb": "gallery-optimized/thumb/IMG_3576.webp",
    "large": "gallery-optimized/large/IMG_3576.webp"
  },
  {
    "id": "IMG_3577",
    "thumb": "gallery-optimized/thumb/IMG_3577.webp",
    "large": "gallery-optimized/large/IMG_3577.webp"
  },
  {
    "id": "IMG_3578",
    "thumb": "gallery-optimized/thumb/IMG_3578.webp",
    "large": "gallery-optimized/large/IMG_3578.webp"
  },
  {
    "id": "IMG_3581",
    "thumb": "gallery-optimized/thumb/IMG_3581.webp",
    "large": "gallery-optimized/large/IMG_3581.webp"
  },
  {
    "id": "IMG_3588",
    "thumb": "gallery-optimized/thumb/IMG_3588.webp",
    "large": "gallery-optimized/large/IMG_3588.webp"
  },
  {
    "id": "IMG_3589",
    "thumb": "gallery-optimized/thumb/IMG_3589.webp",
    "large": "gallery-optimized/large/IMG_3589.webp"
  },
  {
    "id": "IMG_3590",
    "thumb": "gallery-optimized/thumb/IMG_3590.webp",
    "large": "gallery-optimized/large/IMG_3590.webp"
  },
  {
    "id": "IMG_3591",
    "thumb": "gallery-optimized/thumb/IMG_3591.webp",
    "large": "gallery-optimized/large/IMG_3591.webp"
  },
  {
    "id": "IMG_3592",
    "thumb": "gallery-optimized/thumb/IMG_3592.webp",
    "large": "gallery-optimized/large/IMG_3592.webp"
  },
  {
    "id": "IMG_3593",
    "thumb": "gallery-optimized/thumb/IMG_3593.webp",
    "large": "gallery-optimized/large/IMG_3593.webp"
  },
  {
    "id": "IMG_3599",
    "thumb": "gallery-optimized/thumb/IMG_3599.webp",
    "large": "gallery-optimized/large/IMG_3599.webp"
  },
  {
    "id": "IMG_3600",
    "thumb": "gallery-optimized/thumb/IMG_3600.webp",
    "large": "gallery-optimized/large/IMG_3600.webp"
  },
  {
    "id": "IMG_3605",
    "thumb": "gallery-optimized/thumb/IMG_3605.webp",
    "large": "gallery-optimized/large/IMG_3605.webp"
  },
  {
    "id": "IMG_3608",
    "thumb": "gallery-optimized/thumb/IMG_3608.webp",
    "large": "gallery-optimized/large/IMG_3608.webp"
  },
  {
    "id": "IMG_3612",
    "thumb": "gallery-optimized/thumb/IMG_3612.webp",
    "large": "gallery-optimized/large/IMG_3612.webp"
  },
  {
    "id": "IMG_3615",
    "thumb": "gallery-optimized/thumb/IMG_3615.webp",
    "large": "gallery-optimized/large/IMG_3615.webp"
  },
  {
    "id": "IMG_3619",
    "thumb": "gallery-optimized/thumb/IMG_3619.webp",
    "large": "gallery-optimized/large/IMG_3619.webp"
  },
  {
    "id": "IMG_3623",
    "thumb": "gallery-optimized/thumb/IMG_3623.webp",
    "large": "gallery-optimized/large/IMG_3623.webp"
  },
  {
    "id": "IMG_3624",
    "thumb": "gallery-optimized/thumb/IMG_3624.webp",
    "large": "gallery-optimized/large/IMG_3624.webp"
  },
  {
    "id": "IMG_3625",
    "thumb": "gallery-optimized/thumb/IMG_3625.webp",
    "large": "gallery-optimized/large/IMG_3625.webp"
  },
  {
    "id": "IMG_3627",
    "thumb": "gallery-optimized/thumb/IMG_3627.webp",
    "large": "gallery-optimized/large/IMG_3627.webp"
  },
  {
    "id": "IMG_3628",
    "thumb": "gallery-optimized/thumb/IMG_3628.webp",
    "large": "gallery-optimized/large/IMG_3628.webp"
  },
  {
    "id": "IMG_3632",
    "thumb": "gallery-optimized/thumb/IMG_3632.webp",
    "large": "gallery-optimized/large/IMG_3632.webp"
  },
  {
    "id": "IMG_3635",
    "thumb": "gallery-optimized/thumb/IMG_3635.webp",
    "large": "gallery-optimized/large/IMG_3635.webp"
  },
  {
    "id": "IMG_3637",
    "thumb": "gallery-optimized/thumb/IMG_3637.webp",
    "large": "gallery-optimized/large/IMG_3637.webp"
  },
  {
    "id": "IMG_3639",
    "thumb": "gallery-optimized/thumb/IMG_3639.webp",
    "large": "gallery-optimized/large/IMG_3639.webp"
  },
  {
    "id": "IMG_3642",
    "thumb": "gallery-optimized/thumb/IMG_3642.webp",
    "large": "gallery-optimized/large/IMG_3642.webp"
  },
  {
    "id": "IMG_3643",
    "thumb": "gallery-optimized/thumb/IMG_3643.webp",
    "large": "gallery-optimized/large/IMG_3643.webp"
  },
  {
    "id": "IMG_3645",
    "thumb": "gallery-optimized/thumb/IMG_3645.webp",
    "large": "gallery-optimized/large/IMG_3645.webp"
  },
  {
    "id": "IMG_3648",
    "thumb": "gallery-optimized/thumb/IMG_3648.webp",
    "large": "gallery-optimized/large/IMG_3648.webp"
  },
  {
    "id": "IMG_3649",
    "thumb": "gallery-optimized/thumb/IMG_3649.webp",
    "large": "gallery-optimized/large/IMG_3649.webp"
  },
  {
    "id": "IMG_3654",
    "thumb": "gallery-optimized/thumb/IMG_3654.webp",
    "large": "gallery-optimized/large/IMG_3654.webp"
  },
  {
    "id": "IMG_3656",
    "thumb": "gallery-optimized/thumb/IMG_3656.webp",
    "large": "gallery-optimized/large/IMG_3656.webp"
  },
  {
    "id": "IMG_3657",
    "thumb": "gallery-optimized/thumb/IMG_3657.webp",
    "large": "gallery-optimized/large/IMG_3657.webp"
  },
  {
    "id": "IMG_3662",
    "thumb": "gallery-optimized/thumb/IMG_3662.webp",
    "large": "gallery-optimized/large/IMG_3662.webp"
  },
  {
    "id": "IMG_3667",
    "thumb": "gallery-optimized/thumb/IMG_3667.webp",
    "large": "gallery-optimized/large/IMG_3667.webp"
  },
  {
    "id": "IMG_3674",
    "thumb": "gallery-optimized/thumb/IMG_3674.webp",
    "large": "gallery-optimized/large/IMG_3674.webp"
  },
  {
    "id": "IMG_3677",
    "thumb": "gallery-optimized/thumb/IMG_3677.webp",
    "large": "gallery-optimized/large/IMG_3677.webp"
  },
  {
    "id": "IMG_3678",
    "thumb": "gallery-optimized/thumb/IMG_3678.webp",
    "large": "gallery-optimized/large/IMG_3678.webp"
  },
  {
    "id": "IMG_3680",
    "thumb": "gallery-optimized/thumb/IMG_3680.webp",
    "large": "gallery-optimized/large/IMG_3680.webp"
  },
  {
    "id": "IMG_3682",
    "thumb": "gallery-optimized/thumb/IMG_3682.webp",
    "large": "gallery-optimized/large/IMG_3682.webp"
  },
  {
    "id": "IMG_3684",
    "thumb": "gallery-optimized/thumb/IMG_3684.webp",
    "large": "gallery-optimized/large/IMG_3684.webp"
  },
  {
    "id": "IMG_3686",
    "thumb": "gallery-optimized/thumb/IMG_3686.webp",
    "large": "gallery-optimized/large/IMG_3686.webp"
  },
  {
    "id": "IMG_3688",
    "thumb": "gallery-optimized/thumb/IMG_3688.webp",
    "large": "gallery-optimized/large/IMG_3688.webp"
  },
  {
    "id": "IMG_3694",
    "thumb": "gallery-optimized/thumb/IMG_3694.webp",
    "large": "gallery-optimized/large/IMG_3694.webp"
  },
  {
    "id": "IMG_3697",
    "thumb": "gallery-optimized/thumb/IMG_3697.webp",
    "large": "gallery-optimized/large/IMG_3697.webp"
  },
  {
    "id": "IMG_3701",
    "thumb": "gallery-optimized/thumb/IMG_3701.webp",
    "large": "gallery-optimized/large/IMG_3701.webp"
  },
  {
    "id": "IMG_3704",
    "thumb": "gallery-optimized/thumb/IMG_3704.webp",
    "large": "gallery-optimized/large/IMG_3704.webp"
  },
  {
    "id": "IMG_3706",
    "thumb": "gallery-optimized/thumb/IMG_3706.webp",
    "large": "gallery-optimized/large/IMG_3706.webp"
  },
  {
    "id": "IMG_3717",
    "thumb": "gallery-optimized/thumb/IMG_3717.webp",
    "large": "gallery-optimized/large/IMG_3717.webp"
  },
  {
    "id": "IMG_3724",
    "thumb": "gallery-optimized/thumb/IMG_3724.webp",
    "large": "gallery-optimized/large/IMG_3724.webp"
  },
  {
    "id": "IMG_3727",
    "thumb": "gallery-optimized/thumb/IMG_3727.webp",
    "large": "gallery-optimized/large/IMG_3727.webp"
  },
  {
    "id": "IMG_3729",
    "thumb": "gallery-optimized/thumb/IMG_3729.webp",
    "large": "gallery-optimized/large/IMG_3729.webp"
  },
  {
    "id": "IMG_3730",
    "thumb": "gallery-optimized/thumb/IMG_3730.webp",
    "large": "gallery-optimized/large/IMG_3730.webp"
  },
  {
    "id": "IMG_3732",
    "thumb": "gallery-optimized/thumb/IMG_3732.webp",
    "large": "gallery-optimized/large/IMG_3732.webp"
  },
  {
    "id": "IMG_3735",
    "thumb": "gallery-optimized/thumb/IMG_3735.webp",
    "large": "gallery-optimized/large/IMG_3735.webp"
  },
  {
    "id": "IMG_3736",
    "thumb": "gallery-optimized/thumb/IMG_3736.webp",
    "large": "gallery-optimized/large/IMG_3736.webp"
  },
  {
    "id": "IMG_3737",
    "thumb": "gallery-optimized/thumb/IMG_3737.webp",
    "large": "gallery-optimized/large/IMG_3737.webp"
  },
  {
    "id": "IMG_3739",
    "thumb": "gallery-optimized/thumb/IMG_3739.webp",
    "large": "gallery-optimized/large/IMG_3739.webp"
  },
  {
    "id": "IMG_3743",
    "thumb": "gallery-optimized/thumb/IMG_3743.webp",
    "large": "gallery-optimized/large/IMG_3743.webp"
  },
  {
    "id": "IMG_3751",
    "thumb": "gallery-optimized/thumb/IMG_3751.webp",
    "large": "gallery-optimized/large/IMG_3751.webp"
  },
  {
    "id": "IMG_3752",
    "thumb": "gallery-optimized/thumb/IMG_3752.webp",
    "large": "gallery-optimized/large/IMG_3752.webp"
  },
  {
    "id": "IMG_3753",
    "thumb": "gallery-optimized/thumb/IMG_3753.webp",
    "large": "gallery-optimized/large/IMG_3753.webp"
  },
  {
    "id": "IMG_3754",
    "thumb": "gallery-optimized/thumb/IMG_3754.webp",
    "large": "gallery-optimized/large/IMG_3754.webp"
  },
  {
    "id": "IMG_3758",
    "thumb": "gallery-optimized/thumb/IMG_3758.webp",
    "large": "gallery-optimized/large/IMG_3758.webp"
  },
  {
    "id": "IMG_3774",
    "thumb": "gallery-optimized/thumb/IMG_3774.webp",
    "large": "gallery-optimized/large/IMG_3774.webp"
  },
  {
    "id": "IMG_3776",
    "thumb": "gallery-optimized/thumb/IMG_3776.webp",
    "large": "gallery-optimized/large/IMG_3776.webp"
  },
  {
    "id": "IMG_3779",
    "thumb": "gallery-optimized/thumb/IMG_3779.webp",
    "large": "gallery-optimized/large/IMG_3779.webp"
  },
  {
    "id": "IMG_3787",
    "thumb": "gallery-optimized/thumb/IMG_3787.webp",
    "large": "gallery-optimized/large/IMG_3787.webp"
  },
  {
    "id": "IMG_3790",
    "thumb": "gallery-optimized/thumb/IMG_3790.webp",
    "large": "gallery-optimized/large/IMG_3790.webp"
  },
  {
    "id": "IMG_3813",
    "thumb": "gallery-optimized/thumb/IMG_3813.webp",
    "large": "gallery-optimized/large/IMG_3813.webp"
  },
  {
    "id": "IMG_3828",
    "thumb": "gallery-optimized/thumb/IMG_3828.webp",
    "large": "gallery-optimized/large/IMG_3828.webp"
  },
  {
    "id": "IMG_3841",
    "thumb": "gallery-optimized/thumb/IMG_3841.webp",
    "large": "gallery-optimized/large/IMG_3841.webp"
  },
  {
    "id": "IMG_3852",
    "thumb": "gallery-optimized/thumb/IMG_3852.webp",
    "large": "gallery-optimized/large/IMG_3852.webp"
  },
  {
    "id": "IMG_3854",
    "thumb": "gallery-optimized/thumb/IMG_3854.webp",
    "large": "gallery-optimized/large/IMG_3854.webp"
  },
  {
    "id": "IMG_3865",
    "thumb": "gallery-optimized/thumb/IMG_3865.webp",
    "large": "gallery-optimized/large/IMG_3865.webp"
  },
  {
    "id": "IMG_3875",
    "thumb": "gallery-optimized/thumb/IMG_3875.webp",
    "large": "gallery-optimized/large/IMG_3875.webp"
  },
  {
    "id": "IMG_3910",
    "thumb": "gallery-optimized/thumb/IMG_3910.webp",
    "large": "gallery-optimized/large/IMG_3910.webp"
  },
  {
    "id": "IMG_3913",
    "thumb": "gallery-optimized/thumb/IMG_3913.webp",
    "large": "gallery-optimized/large/IMG_3913.webp"
  },
  {
    "id": "IMG_3915",
    "thumb": "gallery-optimized/thumb/IMG_3915.webp",
    "large": "gallery-optimized/large/IMG_3915.webp"
  },
  {
    "id": "IMG_3933",
    "thumb": "gallery-optimized/thumb/IMG_3933.webp",
    "large": "gallery-optimized/large/IMG_3933.webp"
  },
  {
    "id": "IMG_3940",
    "thumb": "gallery-optimized/thumb/IMG_3940.webp",
    "large": "gallery-optimized/large/IMG_3940.webp"
  },
  {
    "id": "IMG_3955",
    "thumb": "gallery-optimized/thumb/IMG_3955.webp",
    "large": "gallery-optimized/large/IMG_3955.webp"
  },
  {
    "id": "IMG_3960",
    "thumb": "gallery-optimized/thumb/IMG_3960.webp",
    "large": "gallery-optimized/large/IMG_3960.webp"
  },
  {
    "id": "IMG_3988",
    "thumb": "gallery-optimized/thumb/IMG_3988.webp",
    "large": "gallery-optimized/large/IMG_3988.webp"
  },
  {
    "id": "IMG_3993",
    "thumb": "gallery-optimized/thumb/IMG_3993.webp",
    "large": "gallery-optimized/large/IMG_3993.webp"
  },
  {
    "id": "IMG_3995",
    "thumb": "gallery-optimized/thumb/IMG_3995.webp",
    "large": "gallery-optimized/large/IMG_3995.webp"
  },
  {
    "id": "IMG_3996",
    "thumb": "gallery-optimized/thumb/IMG_3996.webp",
    "large": "gallery-optimized/large/IMG_3996.webp"
  },
  {
    "id": "IMG_4004",
    "thumb": "gallery-optimized/thumb/IMG_4004.webp",
    "large": "gallery-optimized/large/IMG_4004.webp"
  },
  {
    "id": "IMG_4010",
    "thumb": "gallery-optimized/thumb/IMG_4010.webp",
    "large": "gallery-optimized/large/IMG_4010.webp"
  },
  {
    "id": "IMG_4021",
    "thumb": "gallery-optimized/thumb/IMG_4021.webp",
    "large": "gallery-optimized/large/IMG_4021.webp"
  },
  {
    "id": "IMG_4026",
    "thumb": "gallery-optimized/thumb/IMG_4026.webp",
    "large": "gallery-optimized/large/IMG_4026.webp"
  },
  {
    "id": "IMG_4038",
    "thumb": "gallery-optimized/thumb/IMG_4038.webp",
    "large": "gallery-optimized/large/IMG_4038.webp"
  },
  {
    "id": "IMG_4039",
    "thumb": "gallery-optimized/thumb/IMG_4039.webp",
    "large": "gallery-optimized/large/IMG_4039.webp"
  },
  {
    "id": "IMG_4069",
    "thumb": "gallery-optimized/thumb/IMG_4069.webp",
    "large": "gallery-optimized/large/IMG_4069.webp"
  },
  {
    "id": "IMG_4079",
    "thumb": "gallery-optimized/thumb/IMG_4079.webp",
    "large": "gallery-optimized/large/IMG_4079.webp"
  },
  {
    "id": "IMG_4082",
    "thumb": "gallery-optimized/thumb/IMG_4082.webp",
    "large": "gallery-optimized/large/IMG_4082.webp"
  },
  {
    "id": "IMG_4089",
    "thumb": "gallery-optimized/thumb/IMG_4089.webp",
    "large": "gallery-optimized/large/IMG_4089.webp"
  },
  {
    "id": "IMG_4109",
    "thumb": "gallery-optimized/thumb/IMG_4109.webp",
    "large": "gallery-optimized/large/IMG_4109.webp"
  },
  {
    "id": "IMG_4117",
    "thumb": "gallery-optimized/thumb/IMG_4117.webp",
    "large": "gallery-optimized/large/IMG_4117.webp"
  },
  {
    "id": "IMG_4119",
    "thumb": "gallery-optimized/thumb/IMG_4119.webp",
    "large": "gallery-optimized/large/IMG_4119.webp"
  },
  {
    "id": "IMG_4120",
    "thumb": "gallery-optimized/thumb/IMG_4120.webp",
    "large": "gallery-optimized/large/IMG_4120.webp"
  },
  {
    "id": "IMG_4124",
    "thumb": "gallery-optimized/thumb/IMG_4124.webp",
    "large": "gallery-optimized/large/IMG_4124.webp"
  },
  {
    "id": "IMG_4126",
    "thumb": "gallery-optimized/thumb/IMG_4126.webp",
    "large": "gallery-optimized/large/IMG_4126.webp"
  },
  {
    "id": "IMG_4130",
    "thumb": "gallery-optimized/thumb/IMG_4130.webp",
    "large": "gallery-optimized/large/IMG_4130.webp"
  },
  {
    "id": "IMG_4133",
    "thumb": "gallery-optimized/thumb/IMG_4133.webp",
    "large": "gallery-optimized/large/IMG_4133.webp"
  },
  {
    "id": "IMG_4143",
    "thumb": "gallery-optimized/thumb/IMG_4143.webp",
    "large": "gallery-optimized/large/IMG_4143.webp"
  },
  {
    "id": "IMG_4147",
    "thumb": "gallery-optimized/thumb/IMG_4147.webp",
    "large": "gallery-optimized/large/IMG_4147.webp"
  },
  {
    "id": "IMG_4155",
    "thumb": "gallery-optimized/thumb/IMG_4155.webp",
    "large": "gallery-optimized/large/IMG_4155.webp"
  },
  {
    "id": "IMG_4156",
    "thumb": "gallery-optimized/thumb/IMG_4156.webp",
    "large": "gallery-optimized/large/IMG_4156.webp"
  },
  {
    "id": "IMG_4166",
    "thumb": "gallery-optimized/thumb/IMG_4166.webp",
    "large": "gallery-optimized/large/IMG_4166.webp"
  },
  {
    "id": "IMG_4169",
    "thumb": "gallery-optimized/thumb/IMG_4169.webp",
    "large": "gallery-optimized/large/IMG_4169.webp"
  },
  {
    "id": "IMG_4175",
    "thumb": "gallery-optimized/thumb/IMG_4175.webp",
    "large": "gallery-optimized/large/IMG_4175.webp"
  },
  {
    "id": "IMG_4177",
    "thumb": "gallery-optimized/thumb/IMG_4177.webp",
    "large": "gallery-optimized/large/IMG_4177.webp"
  },
  {
    "id": "IMG_4181",
    "thumb": "gallery-optimized/thumb/IMG_4181.webp",
    "large": "gallery-optimized/large/IMG_4181.webp"
  },
  {
    "id": "IMG_4184",
    "thumb": "gallery-optimized/thumb/IMG_4184.webp",
    "large": "gallery-optimized/large/IMG_4184.webp"
  },
  {
    "id": "IMG_4186",
    "thumb": "gallery-optimized/thumb/IMG_4186.webp",
    "large": "gallery-optimized/large/IMG_4186.webp"
  },
  {
    "id": "IMG_4190",
    "thumb": "gallery-optimized/thumb/IMG_4190.webp",
    "large": "gallery-optimized/large/IMG_4190.webp"
  },
  {
    "id": "IMG_4201",
    "thumb": "gallery-optimized/thumb/IMG_4201.webp",
    "large": "gallery-optimized/large/IMG_4201.webp"
  },
  {
    "id": "IMG_4203",
    "thumb": "gallery-optimized/thumb/IMG_4203.webp",
    "large": "gallery-optimized/large/IMG_4203.webp"
  },
  {
    "id": "IMG_4204",
    "thumb": "gallery-optimized/thumb/IMG_4204.webp",
    "large": "gallery-optimized/large/IMG_4204.webp"
  },
  {
    "id": "IMG_4250",
    "thumb": "gallery-optimized/thumb/IMG_4250.webp",
    "large": "gallery-optimized/large/IMG_4250.webp"
  },
  {
    "id": "IMG_4264",
    "thumb": "gallery-optimized/thumb/IMG_4264.webp",
    "large": "gallery-optimized/large/IMG_4264.webp"
  },
  {
    "id": "IMG_4271",
    "thumb": "gallery-optimized/thumb/IMG_4271.webp",
    "large": "gallery-optimized/large/IMG_4271.webp"
  },
  {
    "id": "IMG_4279",
    "thumb": "gallery-optimized/thumb/IMG_4279.webp",
    "large": "gallery-optimized/large/IMG_4279.webp"
  },
  {
    "id": "IMG_4280",
    "thumb": "gallery-optimized/thumb/IMG_4280.webp",
    "large": "gallery-optimized/large/IMG_4280.webp"
  },
  {
    "id": "IMG_4303",
    "thumb": "gallery-optimized/thumb/IMG_4303.webp",
    "large": "gallery-optimized/large/IMG_4303.webp"
  },
  {
    "id": "IMG_4308",
    "thumb": "gallery-optimized/thumb/IMG_4308.webp",
    "large": "gallery-optimized/large/IMG_4308.webp"
  },
  {
    "id": "IMG_4886",
    "thumb": "gallery-optimized/thumb/IMG_4886.webp",
    "large": "gallery-optimized/large/IMG_4886.webp"
  },
  {
    "id": "IMG_4888",
    "thumb": "gallery-optimized/thumb/IMG_4888.webp",
    "large": "gallery-optimized/large/IMG_4888.webp"
  },
  {
    "id": "IMG_5322",
    "thumb": "gallery-optimized/thumb/IMG_5322.webp",
    "large": "gallery-optimized/large/IMG_5322.webp"
  },
  {
    "id": "IMG_5494",
    "thumb": "gallery-optimized/thumb/IMG_5494.webp",
    "large": "gallery-optimized/large/IMG_5494.webp"
  },
  {
    "id": "IMG_6033",
    "thumb": "gallery-optimized/thumb/IMG_6033.webp",
    "large": "gallery-optimized/large/IMG_6033.webp"
  },
  {
    "id": "IMG_6088",
    "thumb": "gallery-optimized/thumb/IMG_6088.webp",
    "large": "gallery-optimized/large/IMG_6088.webp"
  },
  {
    "id": "IMG_6658",
    "thumb": "gallery-optimized/thumb/IMG_6658.webp",
    "large": "gallery-optimized/large/IMG_6658.webp"
  },
  {
    "id": "Screenshot 2026-07-01 at 12.02.33 PM",
    "thumb": "gallery-optimized/thumb/Screenshot 2026-07-01 at 12.02.33 PM.webp",
    "large": "gallery-optimized/large/Screenshot 2026-07-01 at 12.02.33 PM.webp"
  }
];
