#!/usr/bin/env node
// Scans /gallery, generates compressed web-sized copies, and writes js/gallery-data.js.
// Run this after adding or removing photos: node scripts/build-gallery.js
'use strict';

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const galleryDir = path.join(__dirname, '..', 'gallery');
const thumbDir = path.join(__dirname, '..', 'gallery-optimized', 'thumb');
const largeDir = path.join(__dirname, '..', 'gallery-optimized', 'large');
const outFile = path.join(__dirname, '..', 'js', 'gallery-data.js');
const extensions = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif']);

fs.mkdirSync(thumbDir, { recursive: true });
fs.mkdirSync(largeDir, { recursive: true });

const files = fs.existsSync(galleryDir)
  ? fs.readdirSync(galleryDir).filter((file) => extensions.has(path.extname(file).toLowerCase()))
  : [];

files.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

async function run() {
  const photos = [];

  for (const file of files) {
    const srcPath = path.join(galleryDir, file);
    const outName = path.parse(file).name + '.webp';
    const thumbPath = path.join(thumbDir, outName);
    const largePath = path.join(largeDir, outName);

    try {
      // Thumb: what the grid actually shows — small and cheap to decode.
      await sharp(srcPath)
        .rotate()
        .resize({ width: 480, withoutEnlargement: true })
        .webp({ quality: 68 })
        .toFile(thumbPath);

      // Large: what the lightbox / hero backgrounds show — capped, not the raw original.
      await sharp(srcPath)
        .rotate()
        .resize({ width: 1600, withoutEnlargement: true })
        .webp({ quality: 78 })
        .toFile(largePath);

      const id = path.parse(file).name;
      photos.push({
        id,
        thumb: `gallery-optimized/thumb/${outName}`,
        large: `gallery-optimized/large/${outName}`,
      });
      console.log(`Optimized ${file}`);
    } catch (err) {
      console.warn(`Could not optimize ${file}, falling back to the original: ${err.message}`);
      photos.push({ id: path.parse(file).name, thumb: `gallery/${file}`, large: `gallery/${file}` });
    }
  }

  const banner =
    '// Auto-generated by scripts/build-gallery.js — do not edit by hand.\n' +
    '// Re-run "node scripts/build-gallery.js" after adding/removing photos in /gallery.\n';
  const content = `${banner}window.GALLERY_PHOTOS = ${JSON.stringify(photos, null, 2)};\n`;

  fs.writeFileSync(outFile, content);
  console.log(`Wrote ${photos.length} photo(s) to ${path.relative(process.cwd(), outFile)}`);
}

run();
